# Etapa de desarrollo para React con hot reload
FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

# Exponemos el puerto que usa React en desarrollo
EXPOSE 3000

CMD ["npm", "start"]
