version: "3.9"

services:
  mongo:
    image: mongo:6
    container_name: mongo_db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: backend_app
    restart: always
    env_file:
      - ./backend/.env
    environment:
      - DOCKER_ENV=true
      - USE_MEMORY_DB=false
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - "8080:8080"
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: frontend_app
    restart: always
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  mongo_data:

