services:
  backend:
    image: ignacioalcaniz/fullstack-backend:latest
    container_name: backend
    restart: always
    env_file: ./backend/.env
    ports:
      - "5000:5000"
    depends_on:
      - mongo

  frontend:
    image: ignacioalcaniz/fullstack-frontend:latest
    container_name: frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend

  mongo:
    image: mongo:6
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: fullstackdb
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongo_data:

