FROM node:20-alpine

WORKDIR /app

ENV npm_config_legacy_peer_deps=true

COPY package*.json ./
RUN npm install --legacy-peer-deps

COPY . .

RUN npm install -g nodemon

EXPOSE 8080

CMD ["nodemon", "src/server.js"]
