FROM node:20-alpine

WORKDIR /app

# Copiar dependencias
COPY package*.json ./
RUN npm install

# Copiar el resto del código
COPY . .

# Instalar nodemon para autoreload
RUN npm install -g nodemon

EXPOSE 8080

# Usar nodemon en vez de node
CMD ["nodemon", "src/server.js"]
